# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: About Us
    url: about
    weight: 15
  - name: Blog
    url: blog
    weight: 20
  - name: Opportunities
    url: work-with-us
    weight: 25
  - name: Code of Conduct
    url: code
    weight: 30
  - name: Contact
    url: '#contact'
    weight: 60

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
#  - name: CV
#    url: uploads/resume.pdf
#    weight: 70
